<?xml version="1.0" encoding="utf-8"?><Database Name="chessmasters" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=chessmasters;Persist Security Info=True;User ID=sa" SettingsObjectName="ChessCore.Properties.Settings" SettingsPropertyName="chessmastersConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Games" Member="Games">
    <Type Name="Game">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WhiteUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BlackUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GameData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="GameStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Game" Member="User" ThisKey="WhiteUserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Game1" Member="User1" ThisKey="BlackUserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PreparedGames" Member="PreparedGames">
    <Type Name="PreparedGame">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PreferedColor" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Association Name="User_PreparedGame" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="User_Game" Member="Games" ThisKey="Id" OtherKey="WhiteUserId" Type="Game" />
      <Association Name="User_Game1" Member="Games1" ThisKey="Id" OtherKey="BlackUserId" Type="Game" />
      <Association Name="User_PreparedGame" Member="PreparedGames" ThisKey="Id" OtherKey="UserId" Type="PreparedGame" />
    </Type>
  </Table>
</Database>